// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fghuralujkiddeuncyml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaHVyYWx1amtpZGRldW5jeW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDg4MjgsImV4cCI6MjA1OTUyNDgyOH0.aNwnkOs1-TyYucGJls85baNr3FrYZJ1yr48QlvTapqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);